```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)

#Library for 3D Plotting
library("rgl")
library("knitr")

#View OpenGL plots in HTML
knit_hooks$set(webgl = hook_webgl)
```

<h2>Visualising 2D Gaussians</h2>
<p>The multi-variate Gaussian pdf is given by:
$$ p(\mathbf{x}|\boldsymbol\mu,\boldsymbol\Sigma) = \frac{1}{(2\pi)^{D/2}}\frac{
1}{|\boldsymbol\Sigma|^{1/2}}\exp\left\{-\frac{1}{2}(\mathbf{x} -
\boldsymbol\mu)^T\boldsymbol\Sigma^{-1}(\mathbf{x}-\boldsymbol\mu)\right\} $$
In two dimensions, we can visualise this with contour and surface plots. We
start by defining the mean and covariance.</p>

```{r}
mu <- rbind(c(1, 2)) 
sigma <- matrix(c(1, 0.8, 0.8,1), nrow=2, ncol=2)
```
    
<p>We now define a grid and evaluate the pdf over the grid</p>

```{r}
gaussian_2d <- function(mu, sigma, xvals, yvals) {
  const <- (1.0 / (2.0 * pi)) * (1.0/sqrt(det(sigma)))  
  si <- solve(sigma)
  xv <- xvals - mu[1]
  yv <- yvals - mu[1]

  return (const * exp(-0.5 * (((xv * xv * si[1,1]) + (xv * yv * si[2,1]) +
                               (yv * xv * si[1,2]) + (yv * yv * si[2,2])))))
}

x <- seq(-2, 3.9, by=0.1)
y <- seq(-2, 3.9, by=0.1)
Y <- matrix(rep(x, length(x)), nrow=length(x), ncol=length(x))
X <- t(Y)
Z <- gaussian_2d(mu, sigma, X, Y)
```

<p>Draw a contour of the pdf</p>

```{r}
contour(x,y,Z)
```


<p>Draw a surface of the pdf</p>

```{r, webgl=TRUE}
persp3d(X, Y, Z, col="blue")
```